name: Build and deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Prepare environment
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - run: npm install --global pnpm

      - name: Install deps
        run: pnpm m i

      - name: Build plugin(s)
        run: node ./build.mjs

        # Foolproof feature:
        # - Copies over README so that the root of the deployed website shows it
        # - Changes 404 page to README so that you don't get lost while clicking links
        # If you remove this step then you should probably remove the enable_jekyll option in the next one
      - name: Copy additional files
        run: |
          cp -r public/* dist/

        # Documentation: https://github.com/peaceiris/actions-gh-pages
      - name: Upload pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist

      - name: Deploy
        uses: actions/deploy-pages@v2
